### ISSUE TITLE
Does this code support custom models from transformers library?

### ISSUE THREAD

**Issue by jdf-prog** [poloclub/transformer-explainer#10]
I am wondering if I can deploy a my local custom model with these visualization tools. This will be helpful in inspecting the model's behavior, and help researchers to understand the model's internal states better.

**Comment by gracekimcy** [comment]
Transformer Explainer currently only supports GPT-2 as it is designed to help beginners learn basic transformer concepts, but we hope to support more models in the future!

**Comment by gracekimcy** [comment]
Thanks for asking! We currently do not support custom models, as our tool is designed to help beginners learn basic transformer concepts. However, we hope to support more models in the future!
