### ISSUE TITLE
is it possible to use it with other models?

### ISSUE THREAD

**Issue by deepakdeore2004** [poloclub/transformer-explainer#13]
looks like the the visualization is with gpt2 model which is included in repo itself 
is it possible to run this app with custom model endpoint?

**Comment by LearningForeverMS** [comment]
I also want to know if we can integrate with other llm model. What all code modifications might be required ?

**Comment by gracekimcy** [comment]
Thanks for your interest in Transformer Explainer’s potential to support more models! The ManimML project from our group has been investigating how to enable ML developers more easily create animated visual explanations of ML concepts https://github.com/helblazer811/ManimML . Currently Transformer Explainer does not yet support similar capabilities, but that’s something on our long-term road map.
