### ISSUE TITLE
h: vite: command not found

### ISSUE THREAD

**Issue by fbobe321** [poloclub/transformer-explainer#14]
h: vite: command not found
npm ERR! code ELIFECYCLE
npm ERR! syscall spawn
npm ERR! file sh
npm ERR! errno ENOENT
npm ERR! transformer-explainer@0.0.1 dev: `vite dev`
npm ERR! spawn ENOENT
npm ERR! 
npm ERR! Failed at the transformer-explainer@0.0.1 dev script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.
npm WARN Local package.json exists, but node_modules missing, did you mean to install?

npm ERR! A complete log of this run can be found in:
npm ERR!     /home/bobe/.npm/_logs/2024-08-12T17_07_45_994Z-debug.log

From log:

0 info it worked if it ends with ok
1 verbose cli [ '/usr/bin/node', '/bin/npm', 'run', 'dev' ]
2 info using npm@6.14.11
3 info using node@v10.24.0
4 verbose run-script [ 'predev', 'dev', 'postdev' ]
5 info lifecycle transformer-explainer@0.0.1~predev: transformer-explainer@0.0.1
6 info lifecycle transformer-explainer@0.0.1~dev: transformer-explainer@0.0.1
7 verbose lifecycle transformer-explainer@0.0.1~dev: unsafe-perm in lifecycle true
8 verbose lifecycle transformer-explainer@0.0.1~dev: PATH: /usr/lib/node_modules/npm/node_modules/npm-lifecycle/node-gyp-bin:/home/bobe/transformer-explainer/node_modules/.bin:/home/bobe/.local/bin:/usr/local/cuda/bin:/home/bobe/bin:/home/bobe/.local/bin:/usr/local/cuda/bin:/home/bobe/bin:/home/bobe/.local/bin:/usr/local/cuda/bin:/home/bobe/bin:/home/bobe/.conda/envs/transformer-explainer/bin:/home/bobe/.local/bin:/usr/local/cuda/bin:/home/bobe/bin:/usr/condabin:/sbin:/bin:/usr/bin:/usr/local/bin:/usr/local/sbin:/usr/sbin
9 verbose lifecycle transformer-explainer@0.0.1~dev: CWD: /home/bobe/transformer-explainer
10 silly lifecycle transformer-explainer@0.0.1~dev: Args: [ '-c', 'vite dev' ]
11 info lifecycle transformer-explainer@0.0.1~dev: Failed to exec dev script
12 verbose stack Error: transformer-explainer@0.0.1 dev: `vite dev`
12 verbose stack spawn ENOENT
12 verbose stack     at ChildProcess.<anonymous> (/usr/lib/node_modules/npm/node_modules/npm-lifecycle/lib/spawn.js:48:18)
12 verbose stack     at ChildProcess.emit (events.js:198:13)
12 verbose stack     at maybeClose (internal/child_process.js:982:16)
12 verbose stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:259:5)
13 verbose pkgid transformer-explainer@0.0.1
14 verbose cwd /home/bobe/transformer-explainer
15 verbose Linux 4.18.0-553.8.1.el8_10.x86_64
16 verbose argv "/usr/bin/node" "/bin/npm" "run" "dev"
17 verbose node v10.24.0
18 verbose npm  v6.14.11
19 error code ELIFECYCLE
20 error syscall spawn
21 error file sh
22 error errno ENOENT
23 error transformer-explainer@0.0.1 dev: `vite dev`
23 error spawn ENOENT
24 error Failed at the transformer-explainer@0.0.1 dev script.
24 error This is probably not a problem with npm. There is likely additional logging output above.
25 verbose exit [ 1, true ]

**Comment by aereeeee** [comment]
Hi @fbobe321. Sorry for the late reply! It appears that you are using Node.js version 10. To run the local server, we recommend using Node.js 20 or higher and npm version 10 or higher.
