### ISSUE TITLE
Same input token - different ID values?

### ISSUE THREAD

**Issue by mazurkin** [poloclub/transformer-explainer#15]
Please check the screenshot
![image](https://github.com/user-attachments/assets/2ac34814-44d0-49b4-acc1-2466bc06773f)

Why ID for two instances of "data" ate different?

Also every time I open that section the id values are changing

**Comment by gracekimcy** [comment]
Thank you for bringing this issue to our attention! This issue has now been fixed, and the IDs should remain consistent as expected. Regarding the difference between the two instances of "data," the first token is "Data" while the last token is "data" (with a lowercase 'd' and a space!). You can explore tokenization further with this [tool](https://tiktokenizer.vercel.app/?model=gpt2).
