### ISSUE TITLE
Deploy this to Vercel

### ISSUE THREAD

**Issue by ZhangWei-KUMO** [poloclub/transformer-explainer#16]
Can I deploy this repo to Vercel?

I

**Comment by ZhangWei-KUMO** [comment]
I found the method, the vercel build output dictory is `public`, just modify `svelte.config.js`。
```js
- pages: 'build',
- assets: 'build',
- pages: 'public',
- assets: 'public',
```

**Comment by Vincentqyw** [comment]
Just change the `output directory` from `public` to `build` in `Build & Development Settings` without modifying any code.

**Comment by ZhangWei-KUMO** [comment]
> Just change the `output directory` from `public` to `build` in `Build & Development Settings` without modifying any code.

Thank you for your reply, and I forked it and create a Chinese Edition.

**Comment by aereeeee** [comment]
@Vincentqyw Thanks for your response! The issue seems resolved, so I'll close it.
