### ISSUE TITLE
please provide a docker image

### ISSUE THREAD

**Issue by fw871670784** [poloclub/transformer-explainer#17]
Excuse me，could you provide a Docker image with relevant dependencies already installed? I keep failing to install npm.

***my system info:***
      os Linux 4.19.9
      node v20.16.
      npm  v10.8.
      exit -3
      code -38
 ***and the error is :***
          error code ENOSYS
          error syscall symlink
          error path ../@sveltejs/kit/svelte-kit.js
          error dest /data/XXX/transformer-explainer/node_modules/.bin/svelte-kit
          error errno -38
          error ENOSYS: function not implemented, symlink '../@sveltejs/kit/svelte-kit.js' -> '/data/XXX/transformer-explainer/node_modules/.bin/svelte-kit'

**Comment by aereeeee** [comment]
Hi @fw871670784! 
It seems like your system does not support the `symlink`. I recommend trying the following two solutions.

1. Use the `no-bin-links` option with npm
   ```
   npm install --no-bin-links
   ```

2. Install packages with sudo
   ```
   sudo npm install
   ```
Currently, we do not have plan to provide a Docker image.
